### ISSUE TITLE
[FEATURE] option to choose only to manually sync

### ISSUE THREAD

**Issue by navehay** [photosync/s3#7]

**Comment by tomekit** [comment]
Thanks, we'll be scoping this with our dev team. There would be couple more features required for this to happen (e.g. file selection). At this stage it's hard to give any exact ETA, but we would be looking to deliver it in October.
How would you like this to be working? If you have some additional thoughts, we would be more than happy to include the in our scoping session.

**Comment by tomekit** [comment]
Hi @navehay,

We've actually got it way earlier.
Since 1.4.0, there is an option to disable auto-upload (either per folder or globally in the settings) and then use selection or range-selection (In Gallery, on media item, either double-tap or long-top and choose "Range select" option) in order to sync items of your choice.

Does it work fine for you? Is there anything else you would like to add here?

**Comment by navehay** [comment]
Thanks a lot.

things i wish there were:

1. Option to decide which way to sync (only to servrer, or both ways).
Because i allready deleted unimportant pics and then when i opened the app
only to upload new pics, i saw that it started to download many pics too.

2. Option to delete pics on server alone and locally (without effecting
pics on server)

3. Option to delete locally uploaded pics (like in google.photo)

4. Option to create share link to the cloud

Lets start with these...

Bye
Ariel

בתאריך יום ד׳, 31 באוג׳ 2022, 11:11, מאת Tomasz Raganowicz ‏<
***@***.***>:

**Comment by tomekit** [comment]
Hi @navehay,

We've got next app update. In 1.4.3 release it is possible to create shared albums (currently as beta feature) and delete files remotely.

Two-way sync feature is something we will eventually support, but there are some technical challenges related to maintaining consistent state / versioning. We plan to deliver beta version this year though.

As to deleting locally uploaded pics (like in Google Photo), would you mind explaining it in a bit more detail? 
We will be looking into expanding the album management capabilities anyway, so eventually we will get some of these other features. 

Thanks !

**Comment by tomekit** [comment]
Hi @navehay,
I was wondering how are you finding the updates since 1.4.3 release. 
Am I correct to understand (based on your comments above) that remaining bit to satisfy your use case is to provide option to delete files locally?
I would appreciate if you could let me know if there is anything else that you would find useful.

We've also implemented Feature Requests board (https://syncaware.canny.io/feature-requests), which is bit more convenient way to manage this.

Thanks !

**Comment by navehay** [comment]
I am a bit busy these days. I will look into it in a couple of days BH

בתאריך יום ה׳, 29 בספט׳ 2022, 13:13, מאת Tomasz Raganowicz ‏<
***@***.***>:

**Comment by navehay** [comment]
Hi

I found couple of minutes to answer...

1.Yes. Deleting files locally and on web view will be great.

2. The web view makes 2 problems:

A. It always auto login only on the 2nd attempt. At the 1st attempt i have
to fill the login details manually.

B. It opens the web view with unsequred website warning. Chrome complain
the the certificate is under another name.



בתאריך יום ה׳, 29 בספט׳ 2022, 14:12, מאת א.נ. ***@***.***>:

**Comment by tomekit** [comment]
Thanks for finding time to answer. 

Regarding B), are you using Chrome on mobile or desktop? 

Our certificate is verified and trusted: 
![Screenshot from 2022-10-11 11-12-33](https://user-images.githubusercontent.com/7759113/195051835-f3fa6d1a-5de7-4df8-8723-3a4daa6815a9.png)

Can you perhaps right click on the padlock and display the certificate?
![Screenshot from 2022-10-11 11-11-44](https://user-images.githubusercontent.com/7759113/195052052-52589043-4d3d-424c-9d68-5673e9482ede.png)

If it's desktop browser are you on Windows, Linux or MacOS? 

If you get invalid certificate then it's likely due to some network settings on your side. Are you using proxy or any corporate networks/VPN?

The A) might be related to B), so it's better to resolve B) first.
